# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  redis: <%= ENV["REDIS_URL"] %>
  mailer:
    options:
      from: <%= ENV["MAILER_OPTIONS_FROM"] %>
    url_options:
      host: <%= ENV["MAILER_URL_HOST"] %>
      protocol: <%= ENV["MAILER_URL_PROTOCOL"] %>
    delivery_method: <%= ENV["MAILER_DELIVERY_METHOD"] %>

development:
  <<: *default
  redis: <%= ENV["REDIS_ADDR"] || "redis://redis:6379/9" %> 

# test:
#   secret_key_base: 5ef9365be98bdecf37be80d945596a23a410c6ea2ccd65fde8a65310157434f95c4e2fd2e37363a830d04e36cc954844835cdb48f31bd1442d6ae5285c830d0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
